# This is a basic workflow to help you get started with Actions

name: Percy

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

# Set CI to "false" to allow warnings
env:
  CI: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  percy:
    name: Visual Testing
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: yarn add serve @percy/cli
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        with:
          build: yarn cross-env CI=false yarn build
          start: yarn cross-env CI=false yarn serve
          wait-on: 'http://localhost:9000'
          command: 'yarn cross-env CI=false yarn percy snapshot snapshots.yml'
